### ISSUE TITLE
Can not add the package in Meteor 1.4

### ISSUE THREAD

**Issue by cesar2535** [chrisbutler/meteor-node-sass#3]
Hi chris,

I got the error when I install the package to my new meteor project with `1.4` version.

``` bash
=> Errors while adding packages:

While loading package chrisbutler:node-sass@3.4.2:
error: Command failed:
/Users/Cesar/.meteor/packages/meteor-tool/.1.4.0.16250kg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
module.js:327
throw err;
^

Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous>
(/Users/Cesar/.meteor/packages/chrisbutler_node-sass/.3.4.2.cuagmn++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-cnbd6m/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)

npm ERR! Darwin 15.6.0
npm ERR! argv
"/Users/Cesar/.meteor/packages/meteor-tool/.1.4.0.16250kg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/Cesar/.meteor/packages/meteor-tool/.1.4.0.16250kg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install
--fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/Cesar/.meteor/packages/chrisbutler_node-sass/.3.4.2.cuagmn++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-cnbd6m/npm-debug.log
module.js:327
throw err;
^

Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous>
(/Users/Cesar/.meteor/packages/chrisbutler_node-sass/.3.4.2.cuagmn++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-cnbd6m/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)

npm ERR! Darwin 15.6.0
npm ERR! argv
"/Users/Cesar/.meteor/packages/meteor-tool/.1.4.0.16250kg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/Cesar/.meteor/packages/meteor-tool/.1.4.0.16250kg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install
--fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/Cesar/.meteor/packages/chrisbutler_node-sass/.3.4.2.cuagmn++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-cnbd6m/npm-debug.log
```

**Comment by adamgins** [comment]
Hi, getting this same issue with Meteor 1.3.5.1. on one machine and not on another machine. 
it seems like the `node --version` on the machine that does not work shows 4.4.1 where the one that does shows `v0.11.12`

any ideas, pls?

Update node version is not the issue... as `meteor node -v` show `v0.10.46` ... but we still have issue on machine

**Comment by steve-ross** [comment]
related https://github.com/ForbesLindesay/thread-sleep/issues/11

**Comment by steve-ross** [comment]
You shouldn't need this package in meteor anymore... you can just 

```
meteor npm install --save node-sass
```

**Comment by persac** [comment]
Hi @steve-ross, you're right, except in the case of an dependency: in my case the excellent lookback:emails package. I opened an issue there and asked if they can switch to using the node-sass NPM package instead. However, updating this package to work on Node 4 is perhaps an option in the meantime? No idea how much work this is, though.

Needless to say, switching to the node version of the package would be the best solution.

**Comment by adamgins** [comment]
@persac wondering how you solved this?

**Comment by persac** [comment]
@adamgins I don't remember exactly, all I can see is that I'm using the NPM version now. However, I'm still on Meteor 1.6.0.1 since my project is using CoffeeScript. Did you make any progress or are you still looking for a solution?

**Comment by adamgins** [comment]
Thanks Chris

I think I got it sorted… I coned the repo and used NPM too. The report owner also contacted me and will look into it. 

Adam Ginsburg
adam.ginsburg@buzzy.buzz
tel: +61 411 151 732
www.buzzy.buzz
